# .tarvis.yml
language: node_js # 指定语言环境
node_js:
  - "12" # 指定 NodeJS 版本
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - markendown

#在部署了一遍之后发现，运行 npm install 安装 node 的库时候占据了部署的很大一部分时间，这里有一个技巧，可以将 node_modules 缓存起来，这样可以节省部署的时间。
# cache:
#   directories:
#     - node_modules


install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install hexo-cli -g
  - npm install
  #- source travis_env_init.sh # 执行指定的 shell 脚本来做初始化(原来作者的方式)

script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean
  - hexo generate # Hexo 常规命令，执行清理和生成

after_success: # 在构建成功后要运行的命令，构建失败不会执行，其他同上
  - hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客

notifications: # 设置通知项
  email: true
